# See example: https://jasonet.co/posts/scheduled-actions/#jasonetcocreate-an-issue

name: Create data download reminder
on:
  schedule:
    - cron: '*/15 * * * *'
jobs:
  issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: JasonEtco/create-an-issue@v2
        with:
          filename: .github/ISSUE_TEMPLATE/data_download.md
