# See example: https://jasonet.co/posts/scheduled-actions/#jasonetcocreate-an-issue

name: Create data download reminder
on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:
jobs:
  issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: .github/ISSUE_TEMPLATE/data_download.md
